name: build and test

on:
  push:
    branches: [ "feature/21-webapi-continuous-integration" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet VivaCityWebApi/restore
    - name: Build
      run: dotnet VivaCityWebApi/build --no-restore
    - name: Test
      run: dotnet VivaCityWebApi/test
      env:
        SQLConnectionString: ${{ secrets.SQLConnectionString }}
