name: build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: |
        cd VivaCityWebApi
        dotnet restore
    - name: Build
      run: |
        cd VivaCityWebApi
        dotnet build --no-restore
    - name: Test
      run: |
        cd VivaCityWebApi
        dotnet test
      env:
        SQLConnectionString: ${{ secrets.SQLConnectionString }}
